name: Django github actions test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          pyton-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Linting (flake8)
        run: |
          pip install flake8
          flake8
      - name: Coverage report
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report
      - name: Dango unit testing
        run: |
          python3 manage.py test
